"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _association_card from './association-card.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "association-card": _association_card,
})
